# Content Based Recommendation System: Similarity Measure- Cosine SImilarity  
\begin{align}
Cosine(x,y)= \frac{\sum_{i = 1}^{n}x_i y_i
}{\sqrt{\sum_{i=1}^{n}x_i^2} \sqrt{\sum_{i=1}^{n}y_i^2}}
\end{align}

## Ilustrasi

In [1]:
import numpy as np
import pandas as pd

In [2]:
contoh= pd.DataFrame({
    'Movie':['Terminator', 'Ant Man', 'GOTG Vol 2', '3 Idiots'],
    'Comedy':[0,1,1,1],
    'Action':[1,1,1,0],
    'Scifi':[1,1,1,0],
    'Romantic':[0,1,0,0]
})
contoh

Movie  Comedy  Action  Scifi  Romantic
0  Terminator       0       1      1         0
1     Ant Man       1       1      1         1
2  GOTG Vol 2       1       1      1         0
3    3 Idiots       1       0      0         0

In [3]:
# ant man vs gotg vol 2
(1*1 + 1*1 + 1*1 + 1*0)/((4**(1/2))*(3**(1/2)))

0.8660254037844387

In [4]:
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
cosine_similarity(contoh[contoh['Movie']=='Ant Man'].drop(columns='Movie'),
contoh[contoh['Movie']=='GOTG Vol 2'].drop(columns='Movie')) # cosine similarity antara ant man dan gotg vol 2

array([[0.8660254]])

In [6]:
score=cosine_similarity(contoh[contoh['Movie']=='Ant Man'].drop(columns='Movie'), contoh.drop(columns='Movie')) 
# nilai cosin similarity antara antman dengan film2 lainnya

In [7]:
contoh['score']= score.flatten()

In [8]:
contoh[['Movie','score']].sort_values('score', ascending=False) # score kemiripan dengan film antman

Movie     score
1     Ant Man  1.000000
2  GOTG Vol 2  0.866025
0  Terminator  0.707107
3    3 Idiots  0.500000

Dari hasil score di atas, maka rekomendasi yang paling sesuai untuk item Ant Man adalah GOTG Vol 2, diikuti Terminator, dan terakhir adalah 3 Idiots

## Illustrasi 2

In [9]:
contoh= pd.DataFrame({
    'Movie':['Terminator', 'Ant Man', 'GOTG Vol 2', '3 Idiots'],
    'Comedy':[0,4,3,4],
    'Action':[5,5,5,0],
    'Scifi':[3,5,5,0],
    'Romantic':[0,4,0,0]
})
contoh

Movie  Comedy  Action  Scifi  Romantic
0  Terminator       0       5      3         0
1     Ant Man       4       5      5         4
2  GOTG Vol 2       3       5      5         0
3    3 Idiots       4       0      0         0

In [10]:
# antman vs gotg vol 2
(4*3+5*5+5*5+4*0)/(((4**2+5**2+5**2+4**2)**(1/2))*((3**2+5**2+5**2)**(1/2)))

0.891371527293353

In [11]:
cosine_similarity(contoh[contoh['Movie']=='Ant Man'].drop(columns='Movie'), contoh[contoh['Movie']=='GOTG Vol 2'].drop(columns='Movie'))

array([[0.89137153]])

In [12]:
score=cosine_similarity(contoh[contoh['Movie']=='Ant Man'].drop(columns='Movie'), contoh.drop(columns='Movie'))

In [13]:
contoh['score']=score.flatten()

In [14]:
contoh[['Movie','score']].sort_values('score', ascending=False)

Movie     score
1     Ant Man  1.000000
2  GOTG Vol 2  0.891372
0  Terminator  0.757554
3    3 Idiots  0.441726

Dari hasil score di atas, maka rekomendasi yang paling sesuai untuk item Ant Man adalah GOTG Vol 2, diikuti Terminator, dan terakhir adalah 3 Idiots

## Let's try with Anime Dataset

In [15]:
df_anime= pd.read_csv('anime.csv',usecols=['anime_id','name','genre'])
df_anime

anime_id                                               name  \
0         32281                                     Kimi no Na wa.   
1          5114                   Fullmetal Alchemist: Brotherhood   
2         28977                                           Gintama°   
3          9253                                        Steins;Gate   
4          9969                                      Gintama&#039;   
...         ...                                                ...   
12289      9316       Toushindai My Lover: Minami tai Mecha-Minami   
12290      5543                                        Under World   
12291      5621                     Violence Gekiga David no Hoshi   
12292      6133  Violence Gekiga Shin David no Hoshi: Inma Dens...   
12293     26081                   Yasuji no Pornorama: Yacchimae!!   

                                                   genre  
0                   Drama, Romance, School, Supernatural  
1      Action, Adventure, Drama, Fantasy, Magic, Mili...  
2      Action, Comedy, Historical, Parody, Samurai, S...  
3                                       Sci-Fi, Thriller  
4      Action, Comedy, Historical, Parody, Samurai, S...  
...                                                  ...  
12289                                             Hentai  
12290                                             Hentai  
12291                                             Hentai  
12292                                             Hentai  
12293                                             Hentai  

[12294 rows x 3 columns]

In [16]:
df_anime.isna().sum()

anime_id     0
name         0
genre       62
dtype: int64

In [17]:
df_anime=df_anime.dropna()

In [18]:
df_anime=df_anime.reset_index(drop=True)

In [19]:
df_anime['genre'].value_counts()
# untuk membuat item profil, kita perlu membuat setiap genre menjadi 1 kolom tersendiri

Hentai                                     823
Comedy                                     523
Music                                      301
Kids                                       199
Comedy, Slice of Life                      179
                                          ... 
Adventure, Demons, Military, Mystery         1
Mystery, Seinen                              1
Vampire                                      1
Action, Comedy, Hentai, Mecha                1
Comedy, Drama, Mystery, Police, Shounen      1
Name: genre, Length: 3264, dtype: int64

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
cvr= CountVectorizer(tokenizer= lambda x:x.split(', ')) # pakai koma untuk memecak text genre
genre_a=cvr.fit_transform(df_anime['genre'])
print(cvr.get_feature_names_out())
print(len(cvr.get_feature_names_out()))

['action' 'adventure' 'cars' 'comedy' 'dementia' 'demons' 'drama' 'ecchi'
 'fantasy' 'game' 'harem' 'hentai' 'historical' 'horror' 'josei' 'kids'
 'magic' 'martial arts' 'mecha' 'military' 'music' 'mystery' 'parody'
 'police' 'psychological' 'romance' 'samurai' 'school' 'sci-fi' 'seinen'
 'shoujo' 'shoujo ai' 'shounen' 'shounen ai' 'slice of life' 'space'
 'sports' 'super power' 'supernatural' 'thriller' 'vampire' 'yaoi' 'yuri']
43


In [22]:
genre_a.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
genre=pd.DataFrame(genre_a.toarray(), columns=cvr.get_feature_names_out())
genre.shape

(12232, 43)

In [24]:
genre=pd.concat([df_anime['anime_id'],genre],axis=1)
genre # profil dari item (anime)

anime_id  action  adventure  cars  comedy  dementia  demons  drama  \
0         32281       0          0     0       0         0       0      1   
1          5114       1          1     0       0         0       0      1   
2         28977       1          0     0       1         0       0      0   
3          9253       0          0     0       0         0       0      0   
4          9969       1          0     0       1         0       0      0   
...         ...     ...        ...   ...     ...       ...     ...    ...   
12227      9316       0          0     0       0         0       0      0   
12228      5543       0          0     0       0         0       0      0   
12229      5621       0          0     0       0         0       0      0   
12230      6133       0          0     0       0         0       0      0   
12231     26081       0          0     0       0         0       0      0   

       ecchi  fantasy  ...  shounen ai  slice of life  space  sports  \
0          0        0  ...           0              0      0       0   
1          0        1  ...           0              0      0       0   
2          0        0  ...           0              0      0       0   
3          0        0  ...           0              0      0       0   
4          0        0  ...           0              0      0       0   
...      ...      ...  ...         ...            ...    ...     ...   
12227      0        0  ...           0              0      0       0   
12228      0        0  ...           0              0      0       0   
12229      0        0  ...           0              0      0       0   
12230      0        0  ...           0              0      0       0   
12231      0        0  ...           0              0      0       0   

       super power  supernatural  thriller  vampire  yaoi  yuri  
0                0             1         0        0     0     0  
1                0             0         0        0     0     0  
2                0             0         0        0     0     0  
3                0             0         1        0     0     0  
4                0             0         0        0     0     0  
...            ...           ...       ...      ...   ...   ...  
12227            0             0         0        0     0     0  
12228            0             0         0        0     0     0  
12229            0             0         0        0     0     0  
12230            0             0         0        0     0     0  
12231            0             0         0        0     0     0  

[12232 rows x 44 columns]

### Anime Recommender

In [25]:
# misal user menyukai anime Naruto
df_anime[df_anime['name']=='Naruto'] # anime id 20

anime_id    name                                              genre
841        20  Naruto  Action, Comedy, Martial Arts, Shounen, Super P...

In [26]:
genre[genre['anime_id']==20].drop(columns='anime_id') # profil dari anime yang disuka

action  adventure  cars  comedy  dementia  demons  drama  ecchi  fantasy  \
841       1          0     0       1         0       0      0      0        0   

     game  ...  shounen ai  slice of life  space  sports  super power  \
841     0  ...           0              0      0       0            1   

     supernatural  thriller  vampire  yaoi  yuri  
841             0         0        0     0     0  

[1 rows x 43 columns]

In [27]:
score=cosine_similarity(genre[genre['anime_id']==20].drop(columns='anime_id'), genre.drop(columns='anime_id'))

In [28]:
score.shape # score similarity antara naruto dengan anime2 lain

(1, 12232)

In [29]:
df_anime['score']=score.flatten()

In [30]:
df_score=df_anime[['name','anime_id','score']].copy()

In [31]:
df_score[df_score['anime_id']!=20].sort_values('score', ascending=False).iloc[:10]
# 10 anime teratas yang direkomendasikan untuk user yang menyukai naruto

name  anime_id     score
615                                  Naruto: Shippuuden      1735  1.000000
2996  Naruto Soyokazeden Movie: Naruto to Mashin to ...     10659  1.000000
486                            Boruto: Naruto the Movie     28755  1.000000
1343                                        Naruto x UT     10075  1.000000
1573  Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsu...      6325  1.000000
1103  Boruto: Naruto the Movie - Naruto ga Hokage ni...     32365  1.000000
2458               Naruto Shippuuden: Sunny Side Battle     19511  1.000000
1472        Naruto: Shippuuden Movie 4 - The Lost Tower      8246  1.000000
7617                            Kyutai Panic Adventure!     23933  0.894427
175                              Katekyo Hitman Reborn!      1604  0.894427

Mari kita buat proses di atas menjadi 1 function

In [32]:
def recommend():
    anime= int(input('Masukkan id anime yang kalian sukai: '))
    import numpy as np
    import pandas as pd
    from sklearn.feature_extraction.text import CountVectorizer
    from sklearn.metrics.pairwise import cosine_similarity

    # Buat dataframe dengan judul anime dan genre sebagai kolom
    df_anime=pd.read_csv('anime.csv',usecols=['anime_id','name','genre']).dropna().reset_index(drop=True)

    cvr=CountVectorizer(tokenizer= lambda x:x.split(', '))
    genre_a=cvr.fit_transform(df_anime['genre'])

    genre= pd.DataFrame(genre_a.toarray(),columns=cvr.get_feature_names_out())
    genre= pd.concat([df_anime['anime_id'],genre], axis=1) #item profile


    # hitung cosine similarity

    score= cosine_similarity(genre[genre['anime_id']==anime].drop(columns='anime_id'),genre.drop(columns='anime_id'))
    df_anime['score']=score.flatten()
    df_score= df_anime[['name','anime_id','score']].copy()
    return df_score[df_score['anime_id']!= anime].sort_values('score', ascending = False).iloc[:5]



In [34]:
recommend()

# Content Based Recommendation System: Content Based Filtering
## For 1 User

In [35]:
contoh= pd.DataFrame({
    'movies':['Terminator', 'Interstellar','Ant Man','3 Idiots'],
    'score':[7,9,8,9],
    'action':[1,0,1,0],
    'scifi':[1,1,1,0],
    'adventure':[0,1,1,0],
    'comedy':[0,0,1,1],
    'drama':[0,1,0,1]
})

In [36]:
contoh #item feature matrix

movies  score  action  scifi  adventure  comedy  drama
0    Terminator      7       1      1          0       0      0
1  Interstellar      9       0      1          1       0      1
2       Ant Man      8       1      1          1       1      0
3      3 Idiots      9       0      0          0       1      1

In [37]:
contoh2= contoh.copy().drop(columns='movies')
contoh2

score  action  scifi  adventure  comedy  drama
0      7       1      1          0       0      0
1      9       0      1          1       0      1
2      8       1      1          1       1      0
3      9       0      0          0       1      1

In [38]:
for i in contoh2.drop(columns='score').columns:
    contoh2[i]= contoh2['score']*contoh2[i]
    
contoh2

score  action  scifi  adventure  comedy  drama
0      7       7      7          0       0      0
1      9       0      9          9       0      9
2      8       8      8          8       8      0
3      9       0      0          0       9      9

In [39]:
contoh2.drop(columns='score').sum() #total score masing2 genre

action       15
scifi        24
adventure    17
comedy       17
drama        18
dtype: int64

In [40]:
contoh2.drop(columns='score').sum().sum() # total score keseluruhan

91

In [41]:
user_feature_vector=contoh2.drop(columns='score').sum()/contoh2.drop(columns='score').sum().sum() #user feature vector

In [42]:
user_feature_vector

action       0.164835
scifi        0.263736
adventure    0.186813
comedy       0.186813
drama        0.197802
dtype: float64

In [43]:
contoh_rekom= pd.DataFrame({
    'movies':['Titanic','Martian','GOTG Vol 2'],
    'action':[1,0,1],
    'scifi':[1,1,1],
    'adventure':[0,1,1],
    'comedy':[0,0,1],
    'drama':[0,1,0]
})
contoh_rekom

movies  action  scifi  adventure  comedy  drama
0     Titanic       1      1          0       0      0
1     Martian       0      1          1       0      1
2  GOTG Vol 2       1      1          1       1      0

In [44]:
for i in contoh_rekom.drop(columns='movies').columns:
    contoh_rekom[i]=contoh_rekom[i]*user_feature_vector[i]
    
contoh_rekom

movies    action     scifi  adventure    comedy     drama
0     Titanic  0.164835  0.263736   0.000000  0.000000  0.000000
1     Martian  0.000000  0.263736   0.186813  0.000000  0.197802
2  GOTG Vol 2  0.164835  0.263736   0.186813  0.186813  0.000000

In [45]:
contoh_rekom['rating pred']=contoh_rekom.sum(axis=1)

In [46]:
contoh_rekom

movies    action     scifi  adventure    comedy     drama  rating pred
0     Titanic  0.164835  0.263736   0.000000  0.000000  0.000000     0.428571
1     Martian  0.000000  0.263736   0.186813  0.000000  0.197802     0.648352
2  GOTG Vol 2  0.164835  0.263736   0.186813  0.186813  0.000000     0.802198

untuk user ini, kita akan merekomendasikan film GOTG Vol 2, Martian dan Titanic secara berurutan

## Multiple Users

In [47]:
df_item_feature=pd.DataFrame({
    'movies':['Terminator', 'Interstellar','Ant Man','3 Idiots'],
    'action':[1,0,1,0],
    'scifi':[1,1,1,0],
    'adventure':[0,1,1,0],
    'comedy':[0,0,1,1],
    'drama':[0,1,0,1]
})
df_item_feature

movies  action  scifi  adventure  comedy  drama
0    Terminator       1      1          0       0      0
1  Interstellar       0      1          1       0      1
2       Ant Man       1      1          1       1      0
3      3 Idiots       0      0          0       1      1

In [48]:
df_user_item= pd.DataFrame({
    'users':['user1','user2','user3','user4'],
    'Terminator':[7,8,9,0],
    'Interstellar':[9,0,0,7],
    'Ant Man':[8,6,0,0],
    '3 Idiots':[9,5,10,9]
})
df_user_item

users  Terminator  Interstellar  Ant Man  3 Idiots
0  user1           7             9        8         9
1  user2           8             0        6         5
2  user3           9             0        0        10
3  user4           0             7        0         9

In [49]:
# hitung user feature matrix
user_item= np.array(df_user_item.drop(columns='users'))
item_feature= np.array(df_item_feature.drop(columns='movies'))

n_user=user_item.shape[0]
n_item=user_item.shape[1]
n_feature=item_feature.shape[1]

user_feature=np.empty((n_user,n_feature)) #array kosong berukuran n_user x n_feature

for i in range(n_user):
    user_feature_vector=np.matmul(user_item[i,:],item_feature)
#     print(user_item[i,:])
#     print(user_feature_vector)
    user_feature_vector= user_feature_vector/user_feature_vector.sum()
#     print(user_feature_vector)
    user_feature[i,:]=user_feature_vector

In [50]:
user_feature 


array([[0.16483516, 0.26373626, 0.18681319, 0.18681319, 0.1978022 ],
       [0.28      , 0.28      , 0.12      , 0.22      , 0.1       ],
       [0.23684211, 0.23684211, 0.        , 0.26315789, 0.26315789],
       [0.        , 0.17948718, 0.17948718, 0.23076923, 0.41025641]])

In [51]:
df_user_feature=pd.DataFrame(user_feature, index=df_user_item['users'], columns=df_item_feature.columns[1:])

In [52]:
df_user_feature

action     scifi  adventure    comedy     drama
users                                                   
user1  0.164835  0.263736   0.186813  0.186813  0.197802
user2  0.280000  0.280000   0.120000  0.220000  0.100000
user3  0.236842  0.236842   0.000000  0.263158  0.263158
user4  0.000000  0.179487   0.179487  0.230769  0.410256

In [53]:
# prediksi rating dari film pada df_user_item
user_item_score=np.empty((n_user,n_item)) #array kosong
for i in range(n_user):
    score_=np.matmul(item_feature,user_feature[i,:])
    user_item_score[i,:]=score_


In [54]:
user_item_score

array([[0.42857143, 0.64835165, 0.8021978 , 0.38461538],
       [0.56      , 0.5       , 0.9       , 0.32      ],
       [0.47368421, 0.5       , 0.73684211, 0.52631579],
       [0.17948718, 0.76923077, 0.58974359, 0.64102564]])

In [55]:
user_item

array([[ 7,  9,  8,  9],
       [ 8,  0,  6,  5],
       [ 9,  0,  0, 10],
       [ 0,  7,  0,  9]], dtype=int64)

In [56]:
pd.DataFrame(np.where(user_item==0, user_item_score, 0), columns=df_item_feature['movies'], index= df_user_item['users'])

movies  Terminator  Interstellar   Ant Man  3 Idiots
users                                               
user1     0.000000           0.0  0.000000       0.0
user2     0.000000           0.5  0.000000       0.0
user3     0.000000           0.5  0.736842       0.0
user4     0.179487           0.0  0.589744       0.0

Dari score di atas, user3 bisa direkomendasikan untuk menonton ant man dan interstellar,  
sementara user 4 direkomendasikan film ant man (score untuk terminator terlalu rendah)

In [57]:
# merekomendasikan dari film2 baru
df_item_feature_new=pd.DataFrame({
    'movies':['Titanic','Martian','GOTG Vol 2'],
    'action':[1,0,1],
    'scifi':[1,1,1],
    'adventure':[0,1,1],
    'comedy':[0,0,1],
    'drama':[0,1,0]
})

In [58]:
df_item_feature_new

movies  action  scifi  adventure  comedy  drama
0     Titanic       1      1          0       0      0
1     Martian       0      1          1       0      1
2  GOTG Vol 2       1      1          1       1      0

In [59]:
item_feature_new= np.array(df_item_feature_new.drop(columns='movies'))
# item_feature_new
n_item_new= item_feature_new.shape[0]
# n_item_new
user_item_score_new=np.empty((n_user,n_item_new))

for i in range(n_user):
    user_item_score_=np.matmul(item_feature_new, user_feature[i,:])
    user_item_score_new[i,:]=user_item_score_

In [60]:
pd.DataFrame(user_item_score_new, columns=df_item_feature_new['movies'], index=df_user_item['users']).T

users          user1  user2     user3     user4
movies                                         
Titanic     0.428571   0.56  0.473684  0.179487
Martian     0.648352   0.50  0.500000  0.769231
GOTG Vol 2  0.802198   0.90  0.736842  0.589744

Urutan rekomendasi:
* User 1: GOTG, Martian, Titanic
* User 2: GOTG, Titanic, Martian
* User 3: GOTG, Martian, Titanic
* User 4: Martian,GOTG, Titanic  

## With anime Dataset: 1 user

In [ ]:
df_anime=pd.read_csv('anime.csv', usecols=['anime_id','name','rating', 'genre'])

In [ ]:
# df_anime

In [ ]:
# anime yang disukai user 1
df_anime[df_anime['name'].isin(['Naruto','One Piece','Detective Conan'])] 
# anggap saja ratingnya merupakan rating dari user
# pakai ini untuk mendapatkan user feature vector

In [ ]:
# dataset untuk rekomendasi
df_anime[~df_anime['name'].isin(['Naruto','One Piece','Detective Conan'])].drop(columns='rating')

* dropna
* cari user feature vector
* cari prediksi score untuk anime yang akan direkomendasikan 
* cari 10 rekomendasi anime untuk user

* coba dibuat jadi function

## With Anime: more than 1 users

In [ ]:
df_user_item=pd.DataFrame({
    'user':['user 1','user 2','user 3','user 4'],
    32281:[7,8,9,8],
    431:[9,8,9,7],
    1698:[8,8,8,7],
    4722:[9,7,10,8]
})
df_user_item

coba rekomendasikan 10 anime untuk masing-masing user di atas
#tidak usah dibuat function